### PR TITLE
[do-not-merge] Import code from kinto-signer

### PR DESCRIPTION
**Pull request by leplatrem**
Ref #16 

This PR is more a request for feedback than anything else :) 

Tests pass on Python 3.6 but it might be tedious to port the code for PyPy and Python 2.

### CODE REVIEW

**Comment by leplatrem** [comment]
@ richvdh  do you think it makes sense to work on this? I'd be glad to if you think it's a good idea to join forces....

**Comment by richvdh** [comment]
oh gosh I'd forgotten about this. will try to take a look.

**Comment by leplatrem** [comment]
> @leplatrem are you interested in continuing to work on this?

I'm sorry for letting you down here :/ 

I think I found a more robust approach using Rust, where I can share the same implementation of canonical JSON between Python (pyo3) and JavaScript (WebAssembly). Work in progress: https://github.com/leplatrem/python-canonicaljson-rs/

If you're interested in the changes that I proposed here, I can push some updates based on your comments, otherwise, just we shall just abandon the PR.

**Comment by richvdh** [comment]
@leplatrem honestly I think that if you've found a better solution that works for you, it's probably not worth pursuing this any further.

**Pull request closed without merging**
